src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'somda_users')]
#[ORM\Index(name: 'idx_somda_users__uname', columns: ['username'])]
#[ORM\Index(name: 'idx_somda_users__active', columns: ['active'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'uid')]
    public ?int $id = null;

    #[ORM\Column(nullable: false, options: ['default' => false])]
    public bool $active = false;

    #[ORM\Column(length: 20, nullable: false, options: ['default' => ''])]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 20, minMessage: 'De gebruikersnaam moet minimaal 2 karakters lang zijn', maxMessage: 'De gebruikersnaam mag maximaal 20 karakters lang zijn')]
    public string $username = '';

    #[ORM\Column(length: 100, nullable: true, options: ['default' => ''])]
    public ?string $name = null;

    #[ORM\Column(length: 255, nullable: false, options: ['default' => ''])]
    public string $password = '';

    #[Assert\NotBlank]
    #[Assert\Email(message: 'Dit is geen geldig e-mailadres')]
    #[Assert\Length(
        max: 100,
        maxMessage: 'Het e-mailadres mag maximaal 100 karakters lang zijn'
    )]
    #[ORM\Column(length: 100, nullable: false, options: ['default' => ''])]
    public string $email = '';

    #[ORM\Column(name: 'actkey', length: 13, nullable: true)]
    public ?string $activation_key = null;

    #[ORM\Column(name: 'regdate', type: 'datetime', nullable: true)]
    public ?\DateTime $register_timestamp = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    public ?\DateTime $ban_expire_timestamp = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    public ?\DateTime $last_visit = null;

    /** @var list<string> */
    #[ORM\Column]
    public array $roles = [];

    #[ORM\OneToOne(targetEntity: UserInfo::class, mappedBy: 'user', cascade: ['persist', 'remove'])]
    public ?UserInfo $info = null;

    #[ORM\ManyToMany(targetEntity: Group::class, mappedBy: 'users')]
    private Collection $groups;

    #[ORM\OneToMany(targetEntity: ForumFavorite::class, mappedBy: 'user')]
    private Collection $forum_favorites;

    #[ORM\OneToMany(targetEntity: ForumPostFavorite::class, mappedBy: 'user')]
    private Collection $forum_post_favorites;

    #[ORM\ManyToMany(targetEntity: ForumForum::class, mappedBy: 'moderators')]
    private Collection $moderated_forums;

    #[ORM\OneToMany(targetEntity: Spot::class, mappedBy: 'user')]
    private Collection $spots;

    #[ORM\OneToMany(targetEntity: UserPreferenceValue::class, mappedBy: 'user', cascade: ['persist', 'remove'])]
    private Collection $preferences;

    #[ORM\ManyToMany(targetEntity: News::class, mappedBy: 'user_reads')]
    private Collection $news_reads;

    public function __construct()
    {
        $this->groups = new ArrayCollection();
        $this->forum_favorites = new ArrayCollection();
        $this->forum_post_favorites = new ArrayCollection();
        $this->moderated_forums = new ArrayCollection();
        $this->spots = new ArrayCollection();
        $this->preferences = new ArrayCollection();
        $this->news_reads = new ArrayCollection();
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function getRoles(): array
    {
        $role_array = $this->roles;
        foreach ($this->getGroups() as $group) {
            $role_array = \array_merge($role_array, $group->roles);
        }

        return $role_array;
    }

    public function hasRole(string $role): bool
    {
        return \in_array($role, $this->getRoles());
    }

    public function addRole(string $role): User
    {
        if (!$this->hasRole($role)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function addGroup(Group $group): User
    {
        $this->groups[] = $group;

        return $this;
    }

    /**
     * @return Group[]
     */
    public function getGroups(): array
    {
        return $this->groups->toArray();
    }

    public function addForumFavorite(ForumFavorite $forum_favorite): User
    {
        $this->forum_favorites[] = $forum_favorite;

        return $this;
    }

    /**
     * @return ForumFavorite[]
     */
    public function getForumFavorites(): array
    {
        return $this->forum_favorites->toArray();
    }

    public function isForumFavorite(ForumDiscussion $discussion): bool
    {
        foreach ($this->getForumFavorites() as $forum_favorite) {
            if ($forum_favorite->discussion === $discussion) {
                return true;
            }
        }

        return false;
    }

    public function addForumPostFavorite(ForumPostFavorite $forum_post_favorite): User
    {
        $this->forum_post_favorites[] = $forum_post_favorite;

        return $this;
    }

    /**
     * @return ForumPostFavorite[]
     */
    public function getForumPostFavorites(): array
    {
        return $this->forum_post_favorites->toArray();
    }

    public function isPostFavorite(ForumPost $post): bool
    {
        foreach ($this->getForumPostFavorites() as $post_favorite) {
            if ($post_favorite->post === $post) {
                return true;
            }
        }

        return false;
    }

    public function addModeratedForum(ForumForum $forum_forum): User
    {
        $this->moderated_forums[] = $forum_forum;

        return $this;
    }

    /**
     * @return ForumForum[]
     */
    public function getModeratedForums(): array
    {
        return $this->moderated_forums->toArray();
    }

    public function addSpot(Spot $spot): User
    {
        $this->spots[] = $spot;

        return $this;
    }

    /**
     * @return Spot[]
     */
    public function getSpots(): array
    {
        return $this->spots->toArray();
    }

    public function addPreference(UserPreferenceValue $user_preference_value): User
    {
        $this->preferences[] = $user_preference_value;

        return $this;
    }

    /**
     * @return UserPreferenceValue[]
     */
    public function getPreferences(): array
    {
        return $this->preferences->toArray();
    }

    public function removeAllNewsRead(): void
    {
        foreach ($this->news_reads->toArray() as $news_read) {
            $this->news_reads->removeElement($news_read);
        }
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Banner;
use App\Entity\BannerView;
use App\Entity\ForumCategory;
use App\Entity\ForumDiscussion;
use App\Entity\ForumForum;
use App\Entity\ForumPost;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class ForumController extends BaseController
{
    public const MAX_POSTS_PER_PAGE = 100;

    /**
     * @return Response
     */
    public function indexAction(): Response
    {
        $this->breadcrumbHelper->addPart('general.navigation.forum.index', 'forum', [], true);

        $forumCategories = $this->doctrine->getRepository(ForumCategory::class)->findBy([], ['order' => 'ASC']);
        $categories = [];
        foreach ($forumCategories as $category) {
            $categories[] = [
                'category' => $category,
                'forums' => $this->doctrine->getRepository(ForumForum::class)->findByCategory($category),
            ];
        }

        return $this->render('forum/index.html.twig', ['categories' => $categories]);
    }

    /**
     * @param int $id
     * @return Response|RedirectResponse
     */
    public function forumAction(int $id): Response
    {
        /**
         * @var ForumForum $forum
         */
        $forum = $this->doctrine->getRepository(ForumForum::class)->find($id);
        if (is_null($forum)) {
            return $this->redirectToRoute('forum');
        }

        $this->breadcrumbHelper->addPart('general.navigation.forum.index', 'forum');
        $this->breadcrumbHelper->addPart(
            $forum->getCategory()->getName() . ' == ' . $forum->getName(),
            'forum_forum',
            ['id' => $id, 'name' => $forum->getName()],
            true
        );

        $discussions = $this->doctrine->getRepository(ForumDiscussion::class)->findByForum($forum);
        return $this->render('forum/forum.html.twig', [
            'forum' => $forum,
            'discussions' => $discussions
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @param int|null $pageNumber
     * @param int|null $postId
     * @return Response|RedirectResponse
     */
    public function discussionAction(Request $request, int $id, int $pageNumber = null, int $postId = null): Response
    {
        /**
         * @var ForumDiscussion $discussion
         */
        $discussion = $this->doctrine->getRepository(ForumDiscussion::class)->find($id);
        if (is_null($discussion)) {
            return $this->redirectToRoute('forum');
        }
        if (!$this->mayView($discussion->getForum())) {
            throw new AccessDeniedException();
        }

        $this->breadcrumbHelper->addPart('general.navigation.forum.index', 'forum');
        $this->breadcrumbHelper->addPart(
            $discussion->getForum()->getCategory()->getName() . ' == ' . $discussion->getForum()->getName(),
            'forum_forum',
            ['id' => $discussion->getForum()->getId(), 'name' => $discussion->getForum()->getName()]
        );
        $this->breadcrumbHelper->addPart(
            'Discussie',
            'forum_discussion',
            ['id' => $id, 'name' => $discussion->getTitle()],
            true
        );

        $discussion->setViewed($discussion->getViewed() + 1);
        $this->doctrine->getManager()->flush();

        $numberOfPosts = $this->doctrine->getRepository(ForumDiscussion::class)->getNumberOfPosts($discussion);
        $numberOfPages = floor(($numberOfPosts - 1) / self::MAX_POSTS_PER_PAGE) + 1;
        if (is_null($pageNumber)) {
            $pageNumber = 1;
        }


//TODO postId afhandelen!!

        /**
         * @var ForumPost[] $posts
         */
        $numberOfReadPosts = 0;
        if ($this->userIsLoggedIn()) {
            if ($discussion->getForum()->getType() < 4) {
                $numberOfReadPosts = $this->doctrine->getRepository(ForumDiscussion::class)->getNumberOfReadPosts(
                    $discussion,
                    $this->getUser()
                );
                $pageNumber = floor($numberOfReadPosts / self::MAX_POSTS_PER_PAGE) + 1;
            }
            $posts = $this->doctrine->getRepository(ForumPost::class)->findBy(
                ['discussion' => $discussion],
                ['timestamp' => 'ASC'],
                self::MAX_POSTS_PER_PAGE,
                ($pageNumber - 1) * self::MAX_POSTS_PER_PAGE
            );
            $this->doctrine->getRepository(ForumDiscussion::class)->markPostsAsRead($this->getUser(), $posts);
        } else {
            $posts = $this->doctrine->getRepository(ForumPost::class)->findBy(
                ['discussion' => $discussion],
                ['timestamp' => 'ASC'],
                self::MAX_POSTS_PER_PAGE,
                ($pageNumber - 1) * self::MAX_POSTS_PER_PAGE
            );
        }

        return $this->render('forum/discussion.html.twig', [
            'userIsModerator' => in_array($this->getUser(), $discussion->getForum()->getModerators()),
            'discussion' => $discussion,
            'numberOfPages' => $numberOfPages,
            'pageNumber' => $pageNumber,
            'posts' => $posts,
            'mayPost' => $this->mayPost($discussion->getForum()),
            'numberOfReadPosts' => $numberOfReadPosts,
            'forumBanner' => $this->getForumBanner($request),
        ]);
    }

    /**
     * @param Request $request
     * @return Banner|null
     */
    private function getForumBanner(Request $request): ?Banner
    {
        $banners = $this->doctrine->getRepository(Banner::class)->findBy(
            ['location' => Banner::LOCATION_FORUM, 'active' => true]
        );
        if (count($banners) < 1) {
            return null;
        }
        $forumBanner = $banners[rand(0, count($banners) - 1)];

        // Create a view for this banner
        $bannerView = new BannerView();
        $bannerView
            ->setBanner($forumBanner)
            ->setTimestamp(time())
            ->setIp(inet_pton($request->getClientIp()));
        $this->doctrine->getManager()->persist($bannerView);
        $this->doctrine->getManager()->flush();

        return $forumBanner;
    }

    /**
     * @param ForumForum $forum
     * @return bool
     */
    private function mayView(ForumForum $forum): bool
    {
        if ($forum->getType() === 0) {
            return true;
        }
        if (in_array($forum->getType(), [1, 2, 4])) {
            return $this->userIsLoggedIn();
        }
        return in_array($this->getUser(), $forum->getModerators());
    }

    /**
     * @param ForumForum $forum
     * @return bool
     */
    private function mayPost(ForumForum $forum): bool
    {
        if ($forum->getType() === 4) {
            return false;
        }
        if (in_array($forum->getType(), [0, 1])) {
            return $this->userIsLoggedIn();
        }
        return in_array($this->getUser(), $forum->getModerators());
    }
}

templates/mobile/forum/alert.html.twig
{% extends('mobile/base.html.twig') %}

{% block content %}
    <div><i class="fas fa-comments"></i> Bericht melden uit "{{ post.discussion.title }}"</div>

    <br />
    <p class="info">Gebruik deze functie om de moderators en administrators op de hoogte te stellen van berichten die verkeerd geplaatst zijn of in overtreding zijn met de regels van het forum.</p>
    <br />

    {{ form_start(form, { 'attr': { 'id': 'alert_form' } }) }}
        <table align="center">
            {{ form_row(form.comment) }}
            <tr>
                <td colspan="2">
                    <a class="somda-button" href="#" onclick="$('#alert_form').submit(); return false;">Meld bericht</a>
                    <a class="somda-button" href="{{ path('forum_discussion_post', { 'id': post.discussion.id, 'post_id': post.id, 'name': (post.discussion.title|slug )}) }}">Terug naar het bericht</a>
                </td>
            </tr>
        </table>
    {{ form_end(form) }}

    <br />

    <table align="center">
        {% include 'mobile/forum/post.html.twig' with { 'may_post': false, 'user_is_moderator': false, 'post_is_unread': false } %}
    </table>
{% endblock %}

templates/mobile/forum/discussion.html.twig
{% extends('mobile/base.html.twig') %}

{% block content %}
    {% block wiki %}
        {% if discussion.wikis|length > 0 %}
            <table>
                <tr>
                    <td align="center">
                        Deze forumdiscussie is gekoppeld aan de <a href="http://www.railwiki.nl/" rel="noopener" target="_blank">RailWiki.nl</a> pagina('s):
                        <div class="forum-spacer-row"></div>
                        {% for wiki in discussion.wikis %}
                            <a href="http://www.railwiki.nl/index.php/{{ wiki.wiki }}" rel="noopener" target="_blank">{{ wiki.title ? wiki.title : wiki.wiki }}</a>
                            {% if not loop.last %} - {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            </table>
        {% endif %}
    {% endblock %}

    {% block paginator %}
        {% if numberOfPages > 1 %}
            <div class="forum-spacer-row"></div>
            <strong>Pagina's:</strong>
            {% if page_number > 1 %}<a href="{{ path('forum_discussion_page', { 'id': discussion.id, 'name': (discussion.title|slug), 'page_number': (page_number - 1) }) }}">«</a>{% endif %}
            {% for page in 1..numberOfPages %}
                {% if page != page_number %}<a href="{{ path('forum_discussion_page', { 'id': discussion.id, 'name': (discussion.title|slug), 'page_number': page }) }}">{{ page }}</a>{% else %}{{ page }}{% endif %}
            {% endfor %}
            {% if page_number < numberOfPages %}<a href="{{ path('forum_discussion_page', { 'id': discussion.id, 'name': (discussion.title|slug), 'page_number': (page_number + 1) }) }}">»</a>{% endif %}
            <div class="forum-spacer-row"></div>
        {% endif %}
    {% endblock %}

    {% if user_is_moderator %}
        <p>Met geselecteerd: <a href="#" onclick="moderateNew(); return false;"><i class="fas fa-divide" title="Splits af naar een nieuwe discussie"></i></a></p>
    {% endif %}

    {% if user_is_moderator %}
        <span class="moderator-icons">
            {% if discussion.locked %}
                <a href="{{ path('forum_discussion_moderate', { 'id': discussion.id, 'action': constant('App\\Controller\\ForumModerateController::ACTION_OPEN') }) }}"><i class="fas fa-lock-open" title="Open discussie"></i></a>
            {% else %}
                <a href="{{ path('forum_discussion_moderate', { 'id': discussion.id, 'action': constant('App\\Controller\\ForumModerateController::ACTION_CLOSE') }) }}"><i class="fas fa-lock" title="Sluit discussie"></i></a>
            {% endif %}
            <a href="{{ path('forum_discussion_moderate', { 'id': discussion.id, 'action': constant('App\\Controller\\ForumModerateController::ACTION_MOVE') }) }}"><i class="fas fa-angle-double-right" title="Verplaats discussie"></i></a>
        </span>
        <div class="forum-spacer-row"></div>
     {% endif %}
    {% if discussion.locked %}
        <i class="fas fa-lock"></i>
    {% elseif posts|length > 1 %}
        <i class="fas fa-comments"></i>
    {% else %}
        <i class="fas fa-comment"></i>
    {% endif %}
    {{ discussion.title }}
    <br />Forum: <a href="{{ path('forum_forum', { 'id': discussion.forum.id, 'name': discussion.forum.name|slug }) }}">{{ discussion.forum.category.name }} - {{ discussion.forum.name }}</a>
    <div class="forum-spacer-row"></div>

    {% set first_unread_anchor_done = false %}
    {% for post in posts %}
        {% if new_to_old %}
            {% set post_is_unread = loop.index <= ((number_of_posts - number_of_read_posts) - (constant('App\\Generics\\ForumGenerics::MAX_POSTS_PER_PAGE') * (page_number - 1))) %}
        {% else %}
            {% set post_is_unread = loop.index > (number_of_read_posts - (constant('App\\Generics\\ForumGenerics::MAX_POSTS_PER_PAGE') * (page_number - 1))) %}
        {% endif %}
        {% if loop.index == 5 or loop.index == 55 %}
            {% if forumBanner is not null %}
                <table>
                    <tr>
                        <td><a href="{{ path('banner_click_out', { 'id': forumBanner.id }) }}" rel="noopener sponsored" target="_blank">
                            <img alt="{{ forumBanner.customer.name }} {{ forumBanner.description }}" height="150" src="{{ asset('images/banners/' ~ forumBanner.image) }}" />
                        </a></td>
                        <td><a href="{{ path('advertise') }}">advertentie</a></td>
                    </tr>
                </table>
            {% else %}
                <p class="warn">Tevreden over Somda? Overweeg dan eens een <a href="{{ path('about') }}">vrijwillige donatie</a>, alvast bedankt!</p>
                <div class="forum-spacer-row"></div>
            {% endif %}
        {% endif %}

        <table class="forum-post">{% include('mobile/forum/post.html.twig') %}</table>
        <div class="forum-spacer-row"></div>
        {% if is_granted('ROLE_ADMIN_WIKI') and (discussion.wikis|length) > 0 %}
            <table>
                <tr><td colspan="3">Railwiki.nl:
                    {% if post.wiki_check == 0 %}
                        <span class="background-color-orange" id="wiki_{{ post.id }}">Nog te controleren - <a href="#" onclick="wikiCheck({{ post.id }}, 'ok'); return false;">Markeer als gecontroleerd</a> - <a href="#" onclick="wikiCheck({{ post.id }}, 'na'); return false;">Markeer als niet relevante inhoud</a></span>
                    {% elseif post.wiki_check == 1 %}
                        Verwerkt in de wiki door {{ post.wiki_checker.id|displayUser(post.wiki_checker.username)|raw }}
                    {% else %}
                        Geen relevante inhoud, gecontroleerd door {{ post.wiki_checker.id|displayUser(post.wiki_checker.username)|raw }}
                    {% endif %}
                </td></tr>
            </table>
        {% endif %}
    {% endfor %}

    {% if not first_unread_anchor_done and not new_to_old %}<a id="new_post"></a>{% endif %}

    <div class="forum-spacer-row"></div>

    {{ block('wiki') }}

    {{ block('paginator') }}

    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        <a href="{{ path('forum_unread') }}">Bekijk alle ongelezen berichten</a>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {% if is_granted('ROLE_ADMIN_WIKI') %}
        <script>
            /**
             * @param {integer} post_id
             * @param {string} operation
             */
            function wikiCheck(post_id, operation)
            {
                $.ajax({
                    url: '{{ path('forum_post_wiki_check', { 'id': 1234, 'operation': 'ok' }) }}'.replace('/1234/', '/' + post_id + '/').replace('ok', operation)
                })
                $('#wiki_' + post_id).html('<i class="fas fa-check"></i>');
            }
        </script>
    {% endif %}

    {% if user_is_moderator %}
        <script>
            function moderateNew()
            {
                let post_id_list = '';
                let checkboxes = document.getElementsByTagName('input');
                for (let box = 0; box < checkboxes.length; box++)  {
                    if (checkboxes[box].type === 'checkbox' && checkboxes[box].checked) {
                        post_id_list += checkboxes[box].name.substr(3) + ',';
                    }
                }
                if (post_id_list.length > 0) {
                    document.location = '{{ path('forum_discussion_moderate_split', { 'id': discussion.id, 'post_ids': 'abc' }) }}'.replace('/abc/', '/' + post_id_list + '/');
                } else {
                    alert('Selecteer 1 of meer berichten om af te splitsen');
                }
            }
        </script>
    {% endif %}

    <script>
        /**
         * @param {int} post_id
         */
        function favoritePostAdd(post_id)
        {
            $.ajax({
                url: '{{ path('forum_favorite_post_add', { 'id': 1234 }) }}'.replace('/1234/', '/' + post_id + '/'),
            });
            $('#favorite_box_' + post_id).html('<a href="{{ path('forum_favorites') }}" title="Deze discussie staat in jouw favoriete berichten"><i class="fas fa-hand-holding-heart"></i></a>');
        }
    </script>
{% endblock %}

templates/mobile/forum/discussionMove.html.twig
{% extends('mobile/base.html.twig') %}

{% block content %}
    <div><i class="fas fa-comments"></i> Verplaatsen van "{{ discussion.title }}"</div>

    {{ form_start(form, { 'attr': { 'id': 'move_form' } }) }}
        <table>
            {{ form_row(form.forum) }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <a class="somda-button" href="#" onclick="$('#move_form').submit(); return false;">Verplaatsen</a>
                    <a class="somda-button" href="{{ path('forum_discussion', { 'id': discussion.id, 'name': (discussion.title|slug )}) }}">Terug naar de discussie</a>
                </td>
            </tr>
        </table>
    {{ form_end(form) }}
{% endblock %}

templates/mobile/forum/favorites.html.twig
{% extends('mobile/base.html.twig') %}

{% block content %}
    <br />
    <a class="somda-button" href="{{ path('forum') }}">Terug naar het forumoverzicht</a>
    <br />
    <br />

    <h2>Favoriete discussies</h2>
    <table>
        <tr>
            <th>&nbsp;</th>
            <th nowrap="nowrap">E-mail</th>
            <th>{{ 'forum.discussion.subject'|trans }}</th>
            <th>{{ 'forum.lastPost'|trans }}</th>
        </tr>
        {% for favorite in favorites %}
            <tr id="favorite_row_{{ favorite['id'] }}">
                <td><a href="#" onclick="remove({{ favorite['id'] }}); return false;"><i class="fas fa-times" title="Verwijder discussie uit je favorieten"></i></a></td>
                <td align="center" id="alerting_{{ favorite['id'] }}">{% if favorite['alerting'] == constant('App\\Entity\\ForumFavorite::ALERTING_OFF') %}Nee{% else %}Ja{% endif %}</td>
                <td>
                    <a href="{{ path('forum_discussion', { 'id': favorite['id'], 'name': (favorite['title']|slug) }) }}">{{ favorite['title'] }}</a>
                    {% if not favorite['discussion_read'] %} <i class="fas fa-comment-dots"></i>{% endif %}
                </td>
                <td>{{ favorite['max_post_timestamp']|displayDateTime(true, true) }}</td>
            </tr>
        {% else %}
            <tr><td colspan="8">Je hebt nog geen favoriete discussies</td></tr>
        {% endfor %}
    </table>

    <br />

    <h2>Favoriete berichten</h2>
    <table>
        <tr>
            <th>&nbsp;</th>
            <th>Bericht</th>
            <th>{{ 'forum.discussion.subject'|trans }}</th>
            <th>{{ 'forum.author'|trans }}</th>
        </tr>
        {% for favorite in app.user.forumPostFavorites %}
            <tr id="favorite_post_row_{{ favorite.post.id }}">
                <td><a href="#" onclick="removePost({{ favorite.post.id }}); return false;"><i class="fas fa-times" title="Verwijder bericht uit je favorieten"></i></a></td>
                <td>{{ favorite.post|displayForumPost|raw|slice(0, 50) }}...</td>
                <td><a href="{{ path('forum_discussion_post', { 'id': favorite.post.discussion.id, 'name': (favorite.post.discussion.title|slug), 'post_id': favorite.post.id }) }}">{{ favorite.post.discussion.title }}</a></td>
                <td>{{ favorite.post.author.id|displayUser(favorite.post.author.username)|raw }}</td>
            </tr>
        {% else %}
            <tr><td colspan="8">Je hebt nog geen favoriete berichten</td></tr>
        {% endfor %}
    </table>
{% endblock %}

{% block javascripts %}
    <script>
        /**
         * @param {int} discussion_id
         * @param {boolean} alertingOn
         */
        function toggleAlerting(discussion_id, alertingOn)
        {
            $.ajax({
                url: '{{ path('forum_favorite_toggle', { 'id': '1234', 'alerting': 0 }) }}'.replace('0', alertingOn ? '1' : '0').replace('1234', discussion_id),
            });
            if (alertingOn) {
                $('#alerting_' + discussion_id).html('Ja<br /><a href="#" onclick="toggleAlerting(' + discussion_id + ', false); return false;">Zet uit</a>');
            } else {
                $('#alerting_' + discussion_id).html('Nee<br /><a href="#" onclick="toggleAlerting(' + discussion_id + ', true); return false;">Zet aan</a>');
            }
        }

        /**
         * @param {int} discussion_id
         */
        function remove(discussion_id)
        {
            $.ajax({
                url: '{{ path('forum_favorite_remove', { 'id': '1234' }) }}'.replace('/1234/', '/' + discussion_id + '/'),
            });
            $('#favorite_row_' + discussion_id).remove();
        }

        /**
         * @param {int} post_id
         */
        function removePost(post_id)
        {
            $.ajax({
                url: '{{ path('forum_favorite_post_remove', { 'id': '1234' }) }}'.replace('/1234/', '/' + post_id + '/'),
            });
            $('#favorite_post_row_' + post_id).remove();
        }
    </script>
{% endblock %}